{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMZ/UcIVWsJ5DClv50i8Mq0",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/AnushreeKavaloor/genai-2026/blob/main/Hand_cricket.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "BwqBux4JlrS3",
        "outputId": "c078aca2-0615-4719-c9e8-d34a352545c7"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Enter odd/even: Odd\n",
            "You chose odd.\n",
            "Enter one number between 1 to 9: 8\n",
            "Computer chose 3. Total = 11\n",
            "You won the toss!\n",
            "Enter batting/bowling: Balling\n",
            "Invalid! Enter batting or bowling\n",
            "Enter batting/bowling: Bowling\n",
            "You chose bowling\n",
            "Enter number between 1 to 10: 7\n",
            "Your choice 7 and computer choice 6\n",
            "Still not out\n",
            "Computer score: 6\n",
            "Enter number between 1 to 10: 8\n",
            "Your choice 8 and computer choice 4\n",
            "Still not out\n",
            "Computer score: 10\n",
            "Enter number between 1 to 10: 7\n",
            "Your choice 7 and computer choice 3\n",
            "Still not out\n",
            "Computer score: 13\n",
            "Enter number between 1 to 10: 9\n",
            "Your choice 9 and computer choice 2\n",
            "Still not out\n",
            "Computer score: 15\n",
            "Enter number between 1 to 10: 9\n",
            "Your choice 9 and computer choice 9\n",
            "Computer got out!\n",
            "\n",
            "Target is 16 for you to win\n",
            "Second innings: Your batting\n",
            "Enter number between 1 to 10: 10\n",
            "Your choice 10 and computer choice 9\n",
            "Still not out\n",
            "Your score: 10\n",
            "Enter number between 1 to 10: 8\n",
            "Your choice 8 and computer choice 7\n",
            "Still not out\n",
            "Your score: 18\n",
            "You won!\n",
            "\n",
            "--- Match Over ---\n",
            "Your score: 18\n",
            "Computer score: 15\n",
            "You won the match! 🏆\n"
          ]
        }
      ],
      "source": [
        "import random\n",
        "\n",
        "user_score = 0\n",
        "com_score = 0\n",
        "\n",
        "# --- TOSS ---\n",
        "while True:\n",
        "    user_pick = input(\"Enter odd/even: \").lower()\n",
        "    if user_pick not in [\"odd\", \"even\"]:\n",
        "        print(\"Invalid! Enter odd or even\")\n",
        "    else:\n",
        "        break\n",
        "print(f\"You chose {user_pick}.\")\n",
        "\n",
        "com_select = random.randint(1, 9)\n",
        "while True:\n",
        "    user_select = int(input(\"Enter one number between 1 to 9: \"))\n",
        "    if user_select not in range(1, 10):\n",
        "        print(\"Invalid! Select number between 1 to 9\")\n",
        "    else:\n",
        "        break\n",
        "\n",
        "total = com_select + user_select\n",
        "print(f\"Computer chose {com_select}. Total = {total}\")\n",
        "\n",
        "if total % 2 == 0:\n",
        "    result = \"even\"\n",
        "else:\n",
        "    result = \"odd\"\n",
        "\n",
        "# --- FIRST INNINGS ---\n",
        "if result == user_pick:\n",
        "    print(\"You won the toss!\")\n",
        "    while True:\n",
        "        user_choice = input(\"Enter batting/bowling: \").lower()\n",
        "        if user_choice not in [\"batting\", \"bowling\"]:\n",
        "            print(\"Invalid! Enter batting or bowling\")\n",
        "        else:\n",
        "            break\n",
        "    print(f\"You chose {user_choice}\")\n",
        "\n",
        "    # User won toss - first innings\n",
        "    while True:\n",
        "        while True:\n",
        "            user_move = int(input(\"Enter number between 1 to 10: \"))\n",
        "            if user_move not in range(1, 11):\n",
        "                print(\"Invalid number\")\n",
        "            else:\n",
        "                break\n",
        "        com_move = random.randint(1, 10)\n",
        "        print(f\"Your choice {user_move} and computer choice {com_move}\")\n",
        "\n",
        "        if user_move != com_move:\n",
        "            print(\"Still not out\")\n",
        "            if user_choice == \"batting\":\n",
        "                user_score += user_move\n",
        "                print(f\"Your score: {user_score}\")\n",
        "            else:\n",
        "                com_score += com_move\n",
        "                print(f\"Computer score: {com_score}\")\n",
        "        else:\n",
        "            if user_choice == \"batting\":\n",
        "                print(\"You got out!\")\n",
        "            else:\n",
        "                print(\"Computer got out!\")\n",
        "            break\n",
        "\n",
        "    # --- SECOND INNINGS ---\n",
        "    if user_choice == \"batting\":\n",
        "        target = user_score + 1\n",
        "        print(f\"\\nTarget is {target} for computer\")\n",
        "        print(\"Second innings: Computer batting\")\n",
        "\n",
        "        while True:\n",
        "            while True:\n",
        "                user_move = int(input(\"Enter number between 1 to 10: \"))\n",
        "                if user_move not in range(1, 11):\n",
        "                    print(\"Invalid number\")\n",
        "                else:\n",
        "                    break\n",
        "            com_move = random.randint(1, 10)\n",
        "            print(f\"Your choice {user_move} and computer choice {com_move}\")\n",
        "\n",
        "            if user_move != com_move:\n",
        "                print(\"Still not out\")\n",
        "                com_score += com_move\n",
        "                print(f\"Computer score: {com_score}\")\n",
        "                if com_score >= target:\n",
        "                    print(\"Computer won!\")\n",
        "                    break\n",
        "            else:\n",
        "                print(\"Computer got out!\")\n",
        "                break\n",
        "    else:\n",
        "        target = com_score + 1\n",
        "        print(f\"\\nTarget is {target} for you to win\")\n",
        "        print(\"Second innings: Your batting\")\n",
        "\n",
        "        while True:\n",
        "            while True:\n",
        "                user_move = int(input(\"Enter number between 1 to 10: \"))\n",
        "                if user_move not in range(1, 11):\n",
        "                    print(\"Invalid number\")\n",
        "                else:\n",
        "                    break\n",
        "            com_move = random.randint(1, 10)\n",
        "            print(f\"Your choice {user_move} and computer choice {com_move}\")\n",
        "\n",
        "            if user_move != com_move:\n",
        "                print(\"Still not out\")\n",
        "                user_score += user_move\n",
        "                print(f\"Your score: {user_score}\")\n",
        "                if user_score >= target:\n",
        "                    print(\"You won!\")\n",
        "                    break\n",
        "            else:\n",
        "                print(\"You got out!\")\n",
        "                break\n",
        "\n",
        "else:\n",
        "    # --- COMPUTER WON TOSS ---\n",
        "    print(\"You lose the toss!\")\n",
        "    com_choice = random.choice([\"batting\", \"bowling\"])\n",
        "    print(f\"Computer chose {com_choice}\")\n",
        "\n",
        "    # First innings - computer chose\n",
        "    while True:\n",
        "        while True:\n",
        "            user_move = int(input(\"Enter number between 1 to 10: \"))\n",
        "            if user_move not in range(1, 11):\n",
        "                print(\"Invalid number\")\n",
        "            else:\n",
        "                break\n",
        "        com_move = random.randint(1, 10)\n",
        "        print(f\"Your choice {user_move} and computer choice {com_move}\")\n",
        "\n",
        "        if user_move != com_move:\n",
        "            print(\"Still not out\")\n",
        "            if com_choice == \"batting\":\n",
        "                com_score += com_move\n",
        "                print(f\"Computer score: {com_score}\")\n",
        "            else:\n",
        "                user_score += user_move\n",
        "                print(f\"Your score: {user_score}\")\n",
        "        else:\n",
        "            if com_choice == \"batting\":\n",
        "                print(\"Computer got out!\")\n",
        "            else:\n",
        "                print(\"You got out!\")\n",
        "            break\n",
        "\n",
        "    # --- SECOND INNINGS ---\n",
        "    if com_choice == \"batting\":\n",
        "        target = com_score + 1\n",
        "        print(f\"\\nTarget is {target} for you to win\")\n",
        "        print(\"Second innings: Your batting\")\n",
        "\n",
        "        while True:\n",
        "            while True:\n",
        "                user_move = int(input(\"Enter number between 1 to 10: \"))\n",
        "                if user_move not in range(1, 11):\n",
        "                    print(\"Invalid number\")\n",
        "                else:\n",
        "                    break\n",
        "            com_move = random.randint(1, 10)\n",
        "            print(f\"Your choice {user_move} and computer choice {com_move}\")\n",
        "\n",
        "            if user_move != com_move:\n",
        "                print(\"Still not out\")\n",
        "                user_score += user_move\n",
        "                print(f\"Your score: {user_score}\")\n",
        "                if user_score >= target:\n",
        "                    print(\"You won!\")\n",
        "                    break\n",
        "            else:\n",
        "                print(\"You got out!\")\n",
        "                break\n",
        "    else:\n",
        "        target = user_score + 1\n",
        "        print(f\"\\nTarget is {target} for computer\")\n",
        "        print(\"Second innings: Computer batting\")\n",
        "\n",
        "        while True:\n",
        "            while True:\n",
        "                user_move = int(input(\"Enter number between 1 to 10: \"))\n",
        "                if user_move not in range(1, 11):\n",
        "                    print(\"Invalid number\")\n",
        "                else:\n",
        "                    break\n",
        "            com_move = random.randint(1, 10)\n",
        "            print(f\"Your choice {user_move} and computer choice {com_move}\")\n",
        "\n",
        "            if user_move != com_move:\n",
        "                print(\"Still not out\")\n",
        "                com_score += com_move\n",
        "                print(f\"Computer score: {com_score}\")\n",
        "                if com_score >= target:\n",
        "                    print(\"Computer won!\")\n",
        "                    break\n",
        "            else:\n",
        "                print(\"Computer got out!\")\n",
        "                break\n",
        "\n",
        "# --- FINAL RESULT ---\n",
        "print(\"\\n--- Match Over ---\")\n",
        "print(f\"Your score: {user_score}\")\n",
        "print(f\"Computer score: {com_score}\")\n",
        "\n",
        "if user_score > com_score:\n",
        "    print(\"You won the match! 🏆\")\n",
        "elif com_score > user_score:\n",
        "    print(\"Computer won the match!\")\n",
        "else:\n",
        "    print(\"It's a tie!\")"
      ]
    }
  ]
}